### ISSUE TITLE
Status code 400

### ISSUE THREAD

**Issue by intrlocutr** [akameco/pixiv-app-api#14]
- version: 0.12.1
- `node` version: tested on v8.10.0 and v10.16.3
- `npm` (or `yarn`) version: 3.5.2

**Do you want to request a _feature_ or report a _bug_?:**

Bug

**What is the current behavior?:**

All operations throw a rejected promise: `Error: Request failed with status code 400`

**What is the expected behavior?:**

Server should return status code 200 😛 

**Suggested solution:**

Maybe this API is deprecated...? Not sure, it worked yesterday. Tried a few different node-based pixiv clients to no avail.

**Comment by akameco** [comment]
resolved #15 . Thanks for the reporting 👍
