### ISSUE TITLE
Broken package on npm/yarn registry

### ISSUE THREAD

**Issue by oberdev** [akameco/pixiv-app-api#17]
- version: 0.13.0
- `node` version: v11.15.0
- `npm` (or `yarn`) version: 6.10.3 (1.17.3)

**Do you want to request a _feature_ or report a _bug_?:**
Bug
**What is the current behavior?:**
I can't get new version of library `0.13` as on master branch via yarn add/npm install
After I add or install `0.13` version of package, yarn/package.lock refers to registry with old flow types system
https://registry.npmjs.org/pixiv-app-api/-/pixiv-app-api-0.13.0.tgz
https://registry.yarnpkg.com/pixiv-app-api/-/pixiv-app-api-0.13.0.tgz#aa9e7a14e30a68fbb310561a51dabac33d88bc3a
**Suggested solution:**
Can you update package content on registry please to using typescript types in my project?

**Comment by akameco** [comment]
@oberdev Oh, sorry. The typescript version was released as v0.14. Please upgrade to v0.14.0
