### ISSUE TITLE
Unable import library as typescript module

### ISSUE THREAD

**Issue by oberdev** [akameco/pixiv-app-api#18]
- version: 0.14.0
- `node` version:  12.9.1
- `npm` (or `yarn`) version: 6.11.2 (1.17.3)

I can't import this library as typescript module.
If I use imports like:
`import PixivAppApi from 'pixiv-app-api';`
I get `undefined`
If I import like:
`import * as PixivAppApi from 'pixiv-app-api';`
I get function, but my code falls with:
`TypeError: pixiv_app_api_1.default is not a constructor`
But if I use CommonJS import instead TypeScript import (import library as JavaScript module) class constructor works fine.
`const PixivAppApi = require('pixiv-app-api');`
Could you make TypeScript import with avalible types possible?

**Comment by akameco** [comment]
use `esModuleInterop`.

tsconfig.json

```json
{
  "compilerOptions": {
    "outDir": "dist",
    "esModuleInterop": true,
  },
  "include": ["src"]
}
```
