### ISSUE TITLE
another "status code 400"

### ISSUE THREAD

**Issue by airosB** [akameco/pixiv-app-api#25]
- version: 1.0.2
- `node` version: v10.16.3
- `npm` (or `yarn`) version: 6.11.3

**Do you want to request a _feature_ or report a _bug_?:**
bug 

**What is the current behavior?:**
```
const pixiv = new PixivAppApi(id, password);
pixiv.login(); // 200 ok
await pixiv.userDetail(123456); // Error: Request failed with status code 400
```

v1.0.2で一旦400が出なくなりましたが、本日試したところ再度400となっています。
以前と違いlogin() の時点ではエラーにならず、
userDetails や illustSearch などのメソッドを実行した際に400が返ってきます。

**What is the expected behavior?:**
api should return 200 ok

**Suggested solution:**
API has another braking-changes?

**Comment by Mikubill** [comment]
（日本語下手）エラーは特定なメソッドに限り？エラーメッセージとかより詳しい説明をご提供お願いします。

Can you provide details of the error (eg response content, network/system environment)?

**Comment by austinhuang0131** [comment]
```js
const PixivAppApi = require("pixiv-app-api")
const pixiv = new PixivAppApi({camelcaseKeys: false});

pixiv.login("username", "password").then(p => {
  pixiv.userDetail(123456).then(console.log);
});
```
This is working for me.

**Comment by airosB** [comment]
I tested again and found this was not a bug,
but ["Usage" section of readme.md](https://github.com/akameco/pixiv-app-api/blob/master/readme.md#usage) was simply incorrect.

```js
const test = async () => {
    const PixivAppApi = require("pixiv-app-api");
    const pixivImg = require("pixiv-img");
    const pixiv = new PixivAppApi(id, pass)
    
    // without this line, I got a 400 error.
    await pixiv.login();

    ;(async () => {
      const json = await pixiv.searchIllust('艦これ10000users入り')
      await pixivImg(json.illusts[1].imageUrls.large)
      console.log('finish')
    })();
}

test();
```


this is ok
```
await pixiv.login(); 
```

and this gets 400
```
pixiv.login(); 
```
