### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by haihayta** [akameco/pixiv-app-api#6]
Node version: 9.5.0
npm version: 5.6.0

All the Urls in data sent back from .searchIllust() give me the error 403 Forbidden, i cannot access any of them.

**Comment by akameco** [comment]
@haihayta It works in my own environment.
Please check user name and password.

**Comment by haihayta** [comment]
Sorry for the late answer, about the username and password, im currently using them to login to pixiv everyday, and i dont know exactly but here's one of the link i get, it gives me 403 forbidden when i click. 
`https://i.pximg.net/c/600x1200_90/img-master/img/2018/07/07/20/01/11/69580989_p0_master1200.jpg`
That is link from my test with search term "neko",or do i need a premium account to get access to this ?

**Comment by akameco** [comment]
OK.
This is not a problem of pixiv-app-api.  And no premium account is required.

If you are using chrome, please use `Referer Control`.
https://chrome.google.com/webstore/detail/referer-control/hnkcfpcejkafcihlgbojoidoihckciin?hl=it

And set as below.
![2018-07-11 07 13 21](https://user-images.githubusercontent.com/4002137/42540584-f99bc2a0-84d9-11e8-9291-a426076a86b3.png)

If you want to download it, you can use `pixiv-img` :)
 https://github.com/akameco/pixiv-img

**Comment by akameco** [comment]
pixiv limit referrer.
So we can not see the direct image.
Learn about referrer.

**Comment by afterdelight** [comment]
@akameco
i got 403 error to on https://img-sketch.pximg.net/c!/w=540,f=webp:jpeg/uploads/medium/file/10249351/3638632282963316051.png

what is the Referer Control setting for that domain?
