### ISSUE TITLE
Search Illust without login doesn't work anymore?

### ISSUE THREAD

**Issue by adefirmanf** [akameco/pixiv-app-api#8]
- version:
- `node` version: v9.8.0
- `npm` (or `yarn`) version: 5.6.0

**Do you want to request a _feature_ or report a _bug_?:**
_Bug_ also probably _features_ to change example documentation and error message
**What is the current behavior?:**
constructor without username & password arguments should be working, since on documentation said that. But, it got ```TypeError: Expected a string, got undefined```

**Example**
```
const pixiv = new Pixiv(); // TypeError: Expected a string, got undefined
  pixiv.searchIllust('艦これ10000users入り')
    .then((json) => {
      console.log(json);
    }).catch((err) => {
      console.log(err);
    });
```

**Suggested solution:**
I know, this is due of API behavior, (Refer to commit message) : 
https://github.com/upbit/pixivpy/commit/7bd8e23b0f92aaaf1c168b7efdd2af8cf2de133c

Feature request : 
- [x] Change Error message : `Auth is required. Expected a string, got ${typeof this.username}`
- [x] Update example documentation

**Comment by akameco** [comment]
@adefirmanf Thank you for the reporting :)
PRs Welcome 👍
